version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: tech@fleetloom.in
      PGADMIN_DEFAULT_PASSWORD: AiC7!49"Wv
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: R£Q7D0iz0hz5

    volumes:
      - /postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
  postgres_data:
  pgadmin-data:
